### ISSUE TITLE
[Bug report] Passing Trino connector configuration 'hive.config.resources' encounter error:Column '/tmp/hive-site.xml,/tmp/core-site.xml' cannot be resolved

### ISSUE THREAD

**Issue by danhuawang** [datastrato/trino-cascading-connector#12]
### Version

main branch

### Describe what's wrong

<img width="908" alt="image" src="https://github.com/user-attachments/assets/b233a48e-fa18-492c-8429-830d34aa3c5e">

Double quotes should be replaced by single quotes

### Error message and/or stacktrace

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/a658c110-9c1f-452c-a6ed-a4bac95d41b2">

### How to reproduce

create catalog in Trino:

call gravitino.system.create_catalog(
    'gt_hive',
    'hive',
    map(
        array['metastore.uris', 'trino.bypass.hive.config.resources'],
        array['thrift://trino-ci-hive:9083', "/tmp/hive-site.xml,/tmp/core-site.xml"]
    )
);

**Comment by diqiu50** [comment]
You sql command has a syntax error:
```
array['thrift://trino-ci-hive:9083', "/tmp/hive-site.xml,/tmp/core-site.xml"]
```
should:
```
array['thrift://trino-ci-hive:9083', '/tmp/hive-site.xml,/tmp/core-site.xml']
```

**Comment by danhuawang** [comment]
> @danhuawang Your sql command has a syntax error:
> 
> ```
> array['thrift://trino-ci-hive:9083', "/tmp/hive-site.xml,/tmp/core-site.xml"]
> ```
> 
> should:
> 
> ```
> array['thrift://trino-ci-hive:9083', '/tmp/hive-site.xml,/tmp/core-site.xml']
> ```

Yes ,I mean this syntax error existing in our document, and it should be corrected

**Comment by diqiu50** [comment]
Ok i fix in the pr "https://github.com/apache/gravitino/pull/5295/files"
